image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.csharp
    - eamodio.gitlens
tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https
      cd DarkDungeon
      dotnet restore
      dotnet build
      cd ../DarkDungeon.Tests
      dotnet restore
      dotnet build